- src/shared/log.c
... it is completely useless and use uninitialized `r`.
> Remove some garbage code inherited from `systemd`

- src/ata_id/Makefile.am
It is necessary to include src/udev to the include path, because
ata_id.c includes src/shared/udev-util.h which itself includes
src/udev/udev.h
Fixes issue #102. Exact same pull request as #103, except not using the master branch. Sorry about that.
> src/ata_id/Makefile.am: Fixed compilation error

- configure.ac
- src/accelerometer/Makefile.am
* configure.ac: use LT_LIBM to check for the maths library
* src/accelerometer/Makefile.am: use $(LIBM) instead of -lm in the link
flags
This causes all executables (except accelerometer) and libraries to be
linked without libm, which they do not need.
> Build files: remove extraneous dependency

- src/udev/udev-rules.c
Initialisers for anonymous unions are unknown to gcc-4.5, which is still
quite widely used.
See the following build failure, reported by the Buildroot autobuilders:
http://autobuild.buildroot.org/results/11e/11ebb926b891862e270b9cb39fd2ed4344b736a8/build-end.log
This reverts commit 5cb98078479d93e25099c1cb73fa9c46aa9ccf29.
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
Cc: Tom Gundersen <teg@jklm.no>
> Revert "udev: rules - modernise add_rule a bit"

- configure.ac
- src/shared/missing.h
- src/shared/selinux-util.c
Hi,
Add a patch to disable mallinfo statistics with musl toolchains
which doesn't have struct mallinfo.
Fixes:
selinux-util.c: In function ‘mac_selinux_init’:
selinux-util.c:70:25: error: storage size of ‘before_mallinfo’ isn’t known
struct mallinfo before_mallinfo, after_mallinfo;
Add a second patch for strndupa() which is a GNU extension.
Fixes:
./.libs/libudev-core.a(selinux-util.o): In function `mac_selinux_bind':
selinux-util.c:(.text+0xd94): undefined reference to `strndupa'
collect2: error: ld returned 1 exit status
Best regards,
Romain Naour
> Musl fixes

- rules/60-block.rules
It is often suggested that users set noop on SSDs and it turns out that
udev can do this for users.
Setting noop disables the IO priorization and IO reordering logic inside
the kernel, but leaves front/back merging in place. This reduction in
overhead should increase the number of requests sent to solid state
media to the maximum possible, which is said to improve performance on
SSDs. Unfortunately, few benchmarks try real world work loads with a
clear cache to measure the actual difference.
The benchmarks conducted by Daniel Nashed cleared the cache. They favor
noop, although the workload seems somewhat unrealistic:
http://blog.nashcom.de/nashcomblog.nsf/dx/linux-io-performance-tweek.htm
The BFQ developers' benchmarks on SSDs appear to account for both. They
show noop as being far better …
> Solid state drives should use noop IO elevator

- configure.ac
- rules/Makefile.am
- src/Makefile.am
FTL is not necessarily present on all kernels so it's useful to
have an option to disable this.
Signed-off-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>
> configure.ac: add option to disable mtd_probe

- src/shared/missing.h
- src/udev/udev-builtin-input_id.c
Add missing defines so eudev builds for older kernels such as 2.6
Signed-off-by: Gustavo Sverzut Barbieri <barbieri@profusion.mobi>
> udev-builtin-input_id.c: add missing kernel header defines.

- src/libudev/libudev-util.c
- src/udev/udev-event.c
- src/udev/udev-rules.c
- src/udev/udev.h
- src/udev/udevadm-test.c
This fix is backported from systemd which resolves an issue with whitespace characters in symbolic links created by [e]udev. See systemd/systemd issue # 4833 and systemd/systemd pull request # 4837 for details. This issue was originally observed with some NVMe devices when using eudev 3.2.x and this fix resolves eudev issue # 148.
> always replace spaces in symlinks, unless string_escape=none

- configure.ac
This fix typo on test if having and enable blkid.
> configure.ac: fix typo on blkid

- .github/workflows/build.yml
- autogen.sh
I'm not sure about using those devuan images, though, dyne should be alright?
perhaps the action can be made better?
> add actions workflows to check compilation on glibc and musl (devuan, alpine)

- CONTRIBUTING
Signed-off-by: Ariadne Conill <ariadne@dereferenced.org>
> update CONTRIBUTING to reflect updated governance, clarify systemd commit hash requirements

- src/shared/hashmap.h
It is initialized in hashmap.c:338, and should not be initialized
in the header.
Fixes: #191
Signed-off-by: Ariadne Conill <ariadne@dereferenced.org>
> hashmap: don't initialize devt_hash_ops in the header

- src/shared/missing.h
This is for both 32-bit and 64-bit targets.
> Add getrandom(2) system call number for PowerPC

- rules/50-udev-default.rules
udev rules: add rule to create /dev/ptp_hyperv
As for the KVM case, necessary for network cards with
PTP devices when running a guest on HyperV
systemd-commit: 32e868f058da8b90add00b2958c516241c532b70
Author: Luca Boccassi <luca.boccassi@microsoft.com>
Date:   Fri Feb 26 10:25:31 2021 +0000
> rules/50-udev-default.rules: add PTP entry for Hyper-V/Azure

- src/udev/udev.pc.in
In systemd-udev `udevdir` was deprecated in favor of `udev_dir`.
This causes issues with the [latest release of upower](https://gitlab.freedesktop.org/upower/upower/-/blob/v0.99.17/meson.build#L91-95), which now checks for `udev_dir`, which is not provided by eudev.
This just adds `udev_dir`.
See here:
https://github.com/systemd/systemd/commit/4908de44b0a0409f84a7cdc5641b114d6ce8ba03
Please let me know if there are any issues.
> udev: add udev_dir as synonym of udevdir

- configure.ac
- src/shared/formats-util.h
- src/udev/udevadm-monitor.c
On 32bit arches where time_t is defined as long int and where
sizeof(long)==sizeof(int), PRI_TIME is PRIu32 which is "u" and gcc warns about
ignoring the long part of the integer type. There is no problem besides the
warning.
Use "lu" in the above conditions and PRIu32 in all other 32bit time_t cases.
````
udevadm-monitor.c: In function ‘print_device’:
udevadm-monitor.c:49:16: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘__time_t’ {aka ‘long int’} [-Wformat=]
49 |         printf("%-6s[%"PRI_TIME".%06ld] %-8s %s (%s)\n",
|                ^~~~~~~~
50 |                source,
51 |                ts.tv_sec, ts.tv_nsec/1000,
|                ~~~~~~~~~
|                  |
|                  __time_t {aka long int}
In file included from …
```
> Avoid warning on 32bit

- hwdb/60-sensor.hwdb
- rules/60-sensor.rules
https://github.com/eudev-project/eudev/issues/235
> Systemd PR 24353

- src/udev/udevadm-hwdb.c
In file included from udevadm-hwdb.c:26:
In function ‘freep’,
inlined from ‘adm_hwdb’ at udevadm-hwdb.c:624:38:
../../src/shared/util.h:289:9: warning: ‘free’ called on a pointer to an unallocated object ‘"/usr/etc/udev/hwdb.bin"’ [-Wfree-nonheap-object]
289 |         free(*(void**) p);
|         ^~~~~~~~~~~~~~~~~
../../src/shared/util.h:289:9: warning: ‘free’ called on a pointer to an unallocated object ‘"/usr/etc/udev/hwdb.bin"’ [-Wfree-nonheap-object]
> Do not free a static string

- .gitignore
- configure.ac
- src/Makefile.am
- src/dmi_memory_id/Makefile.am
- src/dmi_memory_id/dmi_memory_id.c
- src/fido_id/Makefile.am
- src/fido_id/fido_id.c
- src/fido_id/fido_id_desc.c
- src/fido_id/fido_id_desc.h
- src/shared/fileio.c
- src/shared/fileio.h
- src/shared/path-util.c
- src/shared/path-util.h
- src/shared/socket-util.h
- src/shared/unaligned.h
- src/shared/util.h
Backport the missing fido_id and dmi_memory_id programs
> Missing tools

- src/v4l_id/v4l_id.c
Kernel versions prior to 3.4 did not have V4L2_CAP_DEVICE_CAPS and compiling against such a kernel will fail.
This patch introduces a version check and makes eudev fall back to v2cap.capabilities on these kernels.
> Fix compile-time issue on very old kernels

- src/libudev/libudev-device.c
> Clear sysattr cache if a null pointer is passed

- src/udev/udev-rules.c
Add /usr/local/lib/udev/rules.d to the places from where rules are parsed
> Add /usr/local/lib/udev/rules.d

- man/udev.7
- man/udev.xml
- src/libudev/libudev-hwdb.c
- src/libudev/libudev.h
Dear eudev developers,
It is not very convenient that libudev can only use /etc/udev/hwdb.bin or <prefix>/lib/udev/hwdb.bin. For Guix, we would like that the hwdb.bin file would be compiled for every used combination of hwdb-providing packages, and then let different users choose the file to use at run-time. The minimum that would work would be to add a single (absolute) file name under UDEV_HWDB_BIN, so that libudev would try that file first (and then, fall back to /etc and <prefix>/lib). This is NOT a path variable. Libudev cannot use multiple hwdb.bin files anyway, so there is no need for a path.
The list of files to try for hwdb.bin is now dynamic, and so we should account for malloc failures. However, `udev_hwdb_validate` is not supposed to be able to fail. So, I think it should be …
> Let libudev find hwdb.bin under UDEV_HWDB_BIN

- man/udev.7
- man/udev.xml
- man/udevadm.8
- man/udevadm.xml
- src/udev/udevadm-hwdb.c
Dear eudev developers,
In Guix, every package is installed in a separate "/usr" prefix. For instance, eudev is installed in "/usr-a/" and upower in "/usr-b/" (except it’s actually "/gnu/store/xxx-eudev-version" and "/gnu/store/yyy-upower-version", whatever). If I want to compile the hwdb database and write it to "/usr-b/lib/udev/hwdb.bin" (with "--usr"), the "--root" argument is insufficient. If I compile with --root=/usr-b, I will end up with "/usr-b/usr-a/lib/udev/hwdb.bin".
I think it would be better to let udevadm hwdb write to an arbitrary file.
What do you think?
Best regards,
Vivien
> Add a generic --output argument to udevadm hwdb

- man/udev.7
- man/udev.xml
- man/udevadm.8
- man/udevadm.xml
- src/shared/conf-files.c
- src/shared/conf-files.h
- src/udev/udevadm-hwdb.c
Dear eudev developers,
It would be useful for a Guix package to let udevadm hwdb --update collect hwdb files from different places in the file system. Usually, this is done with a search path. Here I introduce UDEV_HWDB_PATH, which is searched when compiling hwdb.bin, for hwdb files, in addition to /etc/udev/hwdb.d and /lib/udev/hwdb.d.
What do you think?
Best regards,
Vivien Kraus
> Dynamically get the udevadm hwdb files with a path variable

- man/udev.xml
As discussed in IRC, the reference to /run/udev/hwdb.d is most likely an error.
> More wording fixes for the manual page for udev

- configure.ac
- src/libudev/libudev-device.c
- src/libudev/libudev.h
- src/libudev/libudev.sym
udev_device_has_current_tag
udev_device_get_current_tags_list_entry
both are implemented to return all tags, until the current tag concept comes to eudev.
Closes #249
> Add missing API from 247

- rules/78-sound-card.rules
Pipewire requires ID_PATH to use the same device names as with systemd's udev. Some rules, such as the ones in asahi-audio [1] use those names, and fail if they don't match [2].
On systemd's udev this is instead imported in 71-seat.rules, which we don't have.
[1]: https://github.com/AsahiLinux/asahi-audio
[2]: https://github.com/AsahiLinux/asahi-audio/issues/16
> 78-sound-card.rules: Import ID_PATH early

- src/udev/udev-builtin-path_id.c
This is a [commit from upstream](https://github.com/systemd/systemd/commit/b4c6f71b827d41a4af8007b735edf21ef7609f99) to add /dev/disk/by-path symlinks for nvme devices. I could not get the original commit to apply (at all), so I copied the changes manually and retained the original commit metadata. I verified the changes with an nvme m.2 storage device. Original commit message is as-is below:
```
udev/path_id: introduce support for NVMe devices
This appends the nvme name and namespace identifier attribute the the
PCI path for by-path links. Symlinks like the following are now present:
lrwxrwxrwx. 1 root root 13 Sep 16 12:12 pci-0000:01:00.0-nvme-1 -> ../../nvme0n1
lrwxrwxrwx. 1 root root 15 Sep 16 12:12 pci-0000:01:00.0-nvme-1-part1 -> ../../nvme0n1p1
Cc: Michal Sekletar …
```
> udev/path_id: introduce support for NVMe devices

- rules/80-net-name-slot.rules
If nothing else is available, even a MAC name is better than nothing.
> 80-net-name-slot.rules: consider ID_NET_NAME_MAC as a name

- BUILD
Noticed libtool was missing as a build-dependency for Alpine Linux. Without it, the `./autogen.sh` step would complain about `error: Libtool library used but 'LIBTOOL' is undefined`. This PR just adds libtool to the list of dependencies.
> build: Add libtool as build-dependency for Alpine

- src/shared/missing.h
- src/shared/random-util.c
Current dev_urandom() assumes that reading /dev/urandom will never block regardless if the random pool is fully initialized or not.
This assumption is no longer applicable since linux kerrnel enforces the /dev/urandom entropy initialization from v5.18-rc2 with the commit:
48bff1053c17 ("random: opportunistically initialize on /dev/urandom reads").
With this, when we use the linux v5.18-rc2 or later, dev_urandom() will block if enough random pool is not supplied. It causes the boot delay, typically 1024msec(4msec * 256 = 1024msec) delay to fill the 256 bits entropy for the case CONFIG_HZ=250.
To prevent this boot delay, this commit syncs dev_urandom() implementation to the systemd-udev.
The systemd-udev implementation of reading /dev/urandom is as follows.
- Try to get random with calling …
> random-util.c: sync dev_urandom implementation to systemd-udev

- src/udev/udev-rules.c
`DEBUG` turns on some - apparently untested - code that causes compile errors (see linked GitHub issue). Fixing up the unfinished migration to `strbuf`s solves this problem.
Fixes: 915bf0f60fa7 ("udev: use strbuf to store rules strings")
Closes: #287
> udev-rules: Fix compile errors with `-DDEBUG=1`
